version: '3.3'

services:

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
       - jenkins_data:/var/jenkins_home
    networks:
      - test
    ports:
      - '8080:8080'
      - '50000:50000'

  grafana:
    image: grafana/grafana:7.5.7 
    volumes:
      - my-grafana:/var/lib/mygrafana
    networks:
      - test
    ports:
      - '3000:3000'
  db:
    image: mysql:5.7
    networks:
      - test
    environment:
      MYSQL_DATABASE: 'database'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root123'
    volumes:
      - my-db:/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
networks:
  test:
    driver: bridge

volumes:
  my-grafana:
  my-db:
  jenkins_data:
